modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/kawaiicakes/CSVPrinter/issues"
license = "MIT"

[[mods]]
modId = "csvprinter"
version = "${version}"
displayName = "CSVPrinter"
authors = "kawaiicakes"
description = '''
Automatically create custom block definition CSVs for WorldPainter..
'''
logoFile = "assets/csvprinter/icon.png"

[[dependencies.csvprinter]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.csvprinter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
